services:
  haproxy:
    image: haproxy:3.3-alpine
    container_name: haproxy-gateway
    ports:
      - "5432:5432" # Read/Write Port (routes to whichever node is Primary)
      - "7001:7000" # HAProxy Stats Page — host 7000 is taken by macOS AirPlay Receiver
    volumes:
      - ../haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - pg-ha-net

networks:
  pg-ha-net:
    external: true
